config/routes.rb
# frozen_string_literal: true

Shipit::Engine.routes.draw do
  stack_id_format = %r{[^/]+/[^/]+/[^/]+}
  repository_id_format = %r{[^/]+/[^/]+}
  sha_format = /[\da-f]{6,40}/
  root to: 'stacks#index'

  mount Pubsubstub::StreamAction.new, at: "/events", as: :events

  # Robots
  get '/status/version' => 'status#version', as: :version

  resources :webhooks, only: :create

  # API
  namespace :api do
    root to: 'base#index'
    resources :stacks, only: %i[index create]
    scope '/stacks/*id', id: stack_id_format, as: :stack do
      get '/' => 'stacks#show'
      delete '/' => 'stacks#destroy'
      patch '/' => 'stacks#update'
      post '/refresh' => 'stacks#refresh'
    end

    scope '/stacks/*stack_id', stack_id: stack_id_format, as: :stack do
      get '/ccmenu' => 'ccmenu#show', as: :ccmenu
      resource :lock, only: %i[create update destroy]
      resources :tasks, only: %i[index show] do
        resource :output, only: :show
        member do
          put :abort
        end
      end
      resources :deploys, only: %i[index create] do
        resources :release_statuses, only: %i[create]
      end
      resources :rollbacks, only: %i[create]
      resources :commits, only: %i[index]
      resources :merge_requests, only: %i[index show update destroy]
      post '/task/:task_name' => 'tasks#trigger', as: :trigger_task
      resources :hooks, only: %i[index create show update destroy]
    end

    resources :hooks, only: %i[index create show update destroy]
  end

  scope '/ccmenu/*stack_id', stack_id: stack_id_format, as: :ccmenu_url do
    get '/' => 'ccmenu_url#fetch'
  end

  # Browser extension
  get '/merge_status', action: :show, controller: :merge_status, as: :merge_status
  put '/merge_status/*stack_id/pull/:number', action: :enqueue, controller: :merge_status, id: stack_id_format, as: :enqueue_merge_request
  delete '/merge_status/*stack_id/pull/:number', action: :dequeue, controller: :merge_status, id: stack_id_format, as: :dequeue_merge_request

  # Humans
  resources :api_clients

  resources :repositories, only: %i[new index create]
  scope '/repositories/*id', id: repository_id_format, as: :repository do
    get '/' => 'repositories#show'
    patch '/' => 'repositories#update'
    delete '/' => 'repositories#destroy'
    get :settings, controller: :repositories
    get 'stacks/new' => 'repositories#new_stack'
  end

  scope '/github/auth/github', as: :github_authentication, controller: :github_authentication do
    get :login
    post '/', action: :request
    post :callback
    get :callback
    get :logout
  end

  resources :stacks, only: %i[new create index]
  scope '/*id', id: stack_id_format, as: :stack do
    get '/' => 'stacks#show'
    patch '/' => 'stacks#update'
    delete '/' => 'stacks#destroy'
    get :settings, controller: :stacks
    get :all_tasks, controller: :stacks, as: :tasks_list
    get :statistics, controller: :stacks
    post :refresh, controller: :stacks
    get :refresh, controller: :stacks # For easier design, sorry :/
    post :clear_git_cache, controller: :stacks

    resource :continuous_delivery_schedule, only: %i[show update]
  end

  scope '/task/:id', controller: :tasks do
    get '/', action: :lookup
  end

  scope '/*stack_id', stack_id: stack_id_format, as: :stack do
    get '/commit/:sha/checks' => 'commit_checks#show', as: :commit_checks
    get '/commit/:sha/checks/tail' => 'commit_checks#tail', as: :tail_commit_checks, defaults: { format: :json }

    get '/stats' => 'stats#show', as: :stats

    resources :rollbacks, only: %i[create]
    resources :commits, only: %i[update]
    resources :tasks, only: %i[show] do
      collection do
        get '' => 'tasks#index', as: :index
        get ':definition_id/new' => 'tasks#new', as: :new
        post ':definition_id' => 'tasks#create', as: ''
      end

      member do
        post :abort
        get :tail, defaults: { format: :json }
      end
    end

    resources :deploys, only: %i[show create] do
      get ':sha', sha: sha_format, on: :new, action: :new, as: ''
      member do
        get :rollback
        get :revert
      end

      resources :release_statuses, only: %i[create]
    end

    resources :merge_requests, only: %i[index destroy create]
  end
  get '/stacks/:id' => 'stacks#lookup'

  scope '/*repo', repo: %r{[^/]+/[^/]+}, as: :stack_search do
    get '/' => 'stacks#index'
  end
end

app/models/concerns/shipit/defered_touch.rb
module Shipit
  module DeferedTouch
    extend ActiveSupport::Concern

    SET_KEY = 'shipit:defered_touches'.freeze
    TMP_KEY = "#{SET_KEY}:updating".freeze
    CACHE_KEY = "#{SET_KEY}:scheduled".freeze
    THROTTLE_TTL = 1.second

    included do
      class_attribute :defered_touches, instance_accessor: false
      after_commit :schedule_touches
    end

    class << self
      attr_accessor :enabled

      def touch_now!
        now = Time.now.utc
        fetch do |touches|
          records = []
          touches.each do |model, changes|
            changes.each do |attribute, ids|
              records << [model.where(id: ids).to_a, attribute]
            end
          end

          ActiveRecord::Base.transaction do
            records.each do |instances, attribute|
              instances.each { |i| i.touch(attribute, time: now) }
            end
          end
        end
      end

      private

      def fetch
        fetch_members do |records|
          return if records.empty?
          records = records.each_with_object({}) do |(model, id, attribute), hash|
            attributes = (hash[model] ||= {})
            ids = (attributes[attribute] ||= [])
            ids << id
          end
          yield records.transform_keys(&:constantize)
        end
      end

      def fetch_members
        Shipit.redis.multi do
          Shipit.redis.sunionstore(TMP_KEY, SET_KEY)
          Shipit.redis.del(SET_KEY)
        end

        yield Shipit.redis.smembers(TMP_KEY).map { |r| r.split('|') }

        Shipit.redis.del(TMP_KEY)
      end
    end

    self.enabled = true

    module ClassMethods
      def defered_touch(touches)
        touches = touches.transform_values(&Array.method(:wrap))
        self.defered_touches = touches.flat_map do |association_name, attributes|
          association = reflect_on_association(association_name)
          Array.wrap(attributes).map do |attribute|
            [association.klass.name, association.foreign_key, attribute]
          end
        end
      end
    end

    private

    def schedule_touches
      return unless self.class.defered_touches
      touches = self.class.defered_touches.map { |m, fk, a| [m, self[fk], a].join('|') }
      Shipit.redis.sadd(SET_KEY, touches)
      if DeferedTouch.enabled
        Rails.cache.fetch(CACHE_KEY, expires_in: THROTTLE_TTL) do
          DeferedTouchJob.perform_later
          true
        end
      else
        DeferedTouch.touch_now!
      end
    end
  end
end

app/models/concerns/shipit/deferred_touch.rb
# frozen_string_literal: true

module Shipit
  module DeferredTouch
    extend ActiveSupport::Concern

    SET_KEY = 'shipit:deferred_touches'
    TMP_KEY = "#{SET_KEY}:updating".freeze
    CACHE_KEY = "#{SET_KEY}:scheduled".freeze
    THROTTLE_TTL = 1.second

    included do
      class_attribute :deferred_touches, instance_accessor: false
      after_commit :schedule_touches
    end

    class << self
      attr_accessor :enabled

      def touch_now!
        now = Time.now.utc
        fetch do |touches|
          records = []
          touches.each do |model, changes|
            changes.each do |attribute, ids|
              records << [model.where(id: ids).to_a, attribute]
            end
          end

          ActiveRecord::Base.transaction do
            records.each do |instances, attribute|
              instances.each { |i| i.touch(attribute, time: now) }
            end
          end
        end
      end

      private

      def fetch
        fetch_members do |records|
          return if records.empty?

          records = records.each_with_object({}) do |(model, id, attribute), hash|
            attributes = (hash[model] ||= {})
            ids = (attributes[attribute] ||= [])
            ids << id
          end
          yield records.transform_keys(&:constantize)
        end
      end

      def fetch_members
        Shipit.redis.multi do |transaction|
          transaction.sunionstore(TMP_KEY, SET_KEY)
          transaction.del(SET_KEY)
        end

        yield Shipit.redis.smembers(TMP_KEY).map { |r| r.split('|') }

        Shipit.redis.del(TMP_KEY)
      end
    end

    self.enabled = true

    module ClassMethods
      def deferred_touch(touches)
        touches = touches.transform_values(&Array.method(:wrap))
        self.deferred_touches = touches.flat_map do |association_name, attributes|
          association = reflect_on_association(association_name)
          Array.wrap(attributes).map do |attribute|
            [association.klass.name, association.foreign_key, attribute]
          end
        end
      end
    end

    private

    def schedule_touches
      return unless self.class.deferred_touches

      deferred_touches = self.class.deferred_touches.reject do |m, _fk, _a|
        ActiveRecord::NoTouching.applied_to?(m.constantize)
      end
      return if deferred_touches.empty?

      touches = deferred_touches.map { |m, fk, a| [m, self[fk], a].join('|') }
      Shipit.redis.sadd(SET_KEY, touches)
      if DeferredTouch.enabled
        Rails.cache.fetch(CACHE_KEY, expires_in: THROTTLE_TTL) do
          DeferredTouchJob.perform_later
          true
        end
      else
        DeferredTouch.touch_now!
      end
    end
  end
end

app/models/shipit/anonymous_user.rb
# frozen_string_literal: true

module Shipit
  class AnonymousUser
    def blank?
      true
    end

    def email
      'anonymous@example.com'
    end

    def login
      'anonymous'
    end

    def name
      'Anonymous'
    end

    def avatar_url
      'https://github.com/images/error/octocat_happy.gif'
    end

    def id; end

    def github_id; end

    def logged_in?
      false
    end

    def requires_fresh_login?
      false
    end

    def authorized?
      Shipit.authentication_disabled?
    end

    def repositories_contributed_to
      []
    end

    def stacks_contributed_to
      []
    end

    def avatar_uri
      User::DEFAULT_AVATAR.dup
    end

    def created_at
      Time.at(0).utc
    end
    alias updated_at created_at

    def read_attribute_for_serialization(attr)
      public_send(attr)
    end

    def github_api
      Shipit.github.api
    end

    def serializer_class
      AnonymousUserSerializer
    end

    def marked_for_destruction?
      true
    end
  end
end

app/models/shipit/api_client.rb
# frozen_string_literal: true

module Shipit
  class ApiClient < Record
    InsufficientPermission = Class.new(StandardError)

    belongs_to :creator, class_name: 'User'
    belongs_to :stack, optional: true

    validates :creator, :name, presence: true

    serialize :permissions, coder: Shipit.serialized_column(:permissions, type: Array)
    PERMISSIONS = %w[
      read:stack
      write:stack
      deploy:stack
      lock:stack
      read:hook
      write:hook
    ].freeze
    validates :permissions, subset: { of: PERMISSIONS }

    class << self
      def authenticate(token)
        find_by(id: message_verifier.verify(token).to_i)
      rescue Shipit::SimpleMessageVerifier::InvalidSignature
      end

      def message_verifier
        @message_verifier ||= Shipit::SimpleMessageVerifier.new(Shipit.api_clients_secret)
      end
    end

    def authentication_token
      self.class.message_verifier.generate(id)
    end

    def check_permissions!(operation, scope)
      required_permission = "#{operation}:#{scope}"
      unless permissions.include?(required_permission)
        raise InsufficientPermission, "This operation requires the `#{required_permission}` permission"
      end

      true
    end
  end
end

app/models/shipit/application_record.rb
# frozen_string_literal: true

module Shipit
  class ApplicationRecord < Record
    self.abstract_class = true
  end
end

app/models/shipit/check_run.rb
# frozen_string_literal: true

module Shipit
  class CheckRun < ApplicationRecord
    CONCLUSIONS = %w[success failure neutral cancelled timed_out action_required stale skipped].freeze
    include DeferredTouch
    include Status::Common

    CHECK_RUN_REFRESH_DELAY = 5.seconds

    belongs_to :stack, required: true
    belongs_to :commit, required: true

    deferred_touch commit: :updated_at

    validates :conclusion, inclusion: { in: CONCLUSIONS, allow_nil: true }

    after_create :enable_ci_on_stack

    class << self
      def create_or_update_by!(selector:, attributes: {})
        create!(selector.merge(attributes))
      rescue ActiveRecord::RecordNotUnique
        record = find_by!(selector)

        # Checkruns can jump between states and conclusions, and the github timestamps are low precision and unreliable.
        # Since there's a conflict and the webhook seems older, enqueue a refresh.
        # Persist the received data anyways, in case it is now the canonical data on GitHub despite the timestamp.
        if attributes[:conclusion] != record.conclusion && record.newer_than_webhook?(attributes)
          Rails.logger.warn(
            "Conflicting stale checkrun received. Checkrun id: #{selector[:github_id]}, Details: #{attributes}"
          )
          RefreshCheckRunsJob.set(wait: CHECK_RUN_REFRESH_DELAY).perform_later(commit_id: record.commit_id)
        end

        record.update!(attributes)
        record
      end

      def create_or_update_from_github!(stack_id, github_check_run)
        checkrun_date = parse_newest_date(github_check_run)

        unless checkrun_date
          Rails.logger.warn("No valid timestamp found in checkrun data. Checkrun id: #{github_check_run.id}.")
          RefreshCheckRunsJob.set(wait: CHECK_RUN_REFRESH_DELAY).perform_later(stack_id:)
          return
        end

        create_or_update_by!(
          selector: {
            github_id: github_check_run.id
          },
          attributes: {
            stack_id:,
            name: github_check_run.name,
            conclusion: github_check_run.conclusion,
            title: github_check_run.output.title.to_s.truncate(1_000),
            details_url: github_check_run.details_url,
            html_url: github_check_run.html_url,
            github_updated_at: checkrun_date
          }
        )
      end

      def parse_newest_date(github_check_run)
        started_at = github_check_run.started_at
        completed_at = github_check_run.completed_at

        started_at_date = Time.parse(started_at.to_s) if started_at
        completed_at_date = Time.parse(completed_at.to_s) if completed_at

        [started_at_date, completed_at_date].compact.max
      end
    end

    def state
      case conclusion
      when nil, 'action_required'
        'pending'
      when 'success', 'neutral', 'skipped'
        'success'
      when 'failure', 'cancelled', 'stale'
        'failure'
      when 'timed_out'
        'error'
      else
        'unknown'
      end
    end

    def context
      name
    end

    def target_url
      html_url
    end

    def description
      title
    end

    def to_partial_path
      'shipit/statuses/status'
    end

    def newer_than_webhook?(webhook_attributes)
      github_updated_at && github_updated_at >= webhook_attributes[:github_updated_at]
    end

    private

    def enable_ci_on_stack
      commit.stack.enable_ci!
    end
  end
end

app/models/shipit/ci_jobs_status.rb
# frozen_string_literal: true

module Shipit
  class CiJobsStatus < Record
    belongs_to :predictive_build, optional: true
    belongs_to :predictive_branch, optional: true

    state_machine :status, initial: :running do
      state :running
      state :failed
      state :aborted
      state :completed

      event :running do
        transition any => :running
      end

      event :failed do
        transition any => :failed
      end

      event :aborted do
        transition any => :aborted
      end

      event :completed do
        transition any => :completed
      end

      after_transition :running => %i(failed aborted completed) do |ci_jobs_status|
        ci_jobs_status.set_metrics
      end
    end

    def set_metrics
      if predictive_build.present?
        pipeline = predictive_build.pipeline.id.to_s
        stack_name = predictive_build.pipeline.name
      elsif predictive_branch.present?
        pipeline = predictive_branch.predictive_build.pipeline.id.to_s
        stack_name = predictive_branch.stack.repository.full_name
      else
        pipeline = 'unknown'
        stack_name = 'unknown'
      end
      labels = {pipeline: pipeline, stack: stack_name, type: name, status: status.to_s, executor: 'External'}
      seconds = (updated_at - created_at).to_i
      ApplicationMetrics.increment_counter(:shipit_task_count, labels)
      ApplicationMetrics.increment_counter(:shipit_task_duration_seconds_sum, labels, seconds)
    rescue Exception => e
      puts "Shipit::CiJobsStatus#set_metrics - Error: #{e.message}"
    end

    def update_status(status_name)
      case status_name
      when :running
        running
        return
      when :failed
        failed
        return
      when :aborted
        aborted
        return
      when :success, :completed
        completed
        return
      end
    end

  end
end

app/views/shipit/tasks/_task.html.erb
<% cache task do %>
  <%- read_only ||= false -%>

  <li class="task" id="task-<%= task.id %>" data-status="<%= task.status %>">
    <% cache task.author do %>
      <%= render 'shipit/shared/author', author: task.author %>
    <% end %>
    <a href="<%= stack_task_path(@stack, task) %>" class="status status--<%= task.status %>" data-tooltip="<%= task.status.capitalize %>">
      <i class="status__icon"></i>
      <span class="visually-hidden"><%= task.status %></span>
    </a>

    <div class="commit-details">
      <span class="commit-title">
        <a href="<%= stack_task_path(@stack, task) %>">
          <%= task.title %>
        </a>
      </span>
      <p class="commit-meta">
        ran a command
        <% if task.ignored_safeties? %><span class="ignored-safeties">ignoring safeties</span><% end %>
      </p>
      <p class="commit-meta">
        <% if read_only %>
          <span class="utc-timecode">on <%= task.created_at.strftime('%Y-%m-%d %H:%M:%S') %> UTC</span>
        <% else %>
          <%= timeago_tag(task.created_at, force: false, date_only: false, limit: 12.hours.ago, format: '%Y-%m-%d %H:%M %Z') %>
        <% end %>
      </p>
    </div>
  </li>
<% end %>

app/views/shipit/tasks/_task_output.html.erb
<% content_for :main_classes do %>no-footer<% end %>

<%= javascript_include_tag 'task' %>
<%= render partial: 'shipit/stacks/header', locals: { stack: @stack } %>

<div class="sidebar">
  <div class="sidebar-plugins"></div>
</div>

<div class="deploy-main" data-task="<%= {repo: @stack.github_repo_name, description: task.title}.to_json %>">
  <span class="deploy-tasks"></span>
  <div class="deploy-banner" data-status="<%= task.status %>">
    <div class="deploy-banner-status"></div>
    <div class="deploy-banner-section stack-link">
      <%= link_to "Return to #{@stack.repo_name}/#{@stack.environment}", stack_path(@stack) %>
    </div>
    <div class="deploy-banner-section">
      <a href="#" class="user main-user disabled"><%= task.author.name %></a>
      <span class="deploy-status">
        <%= content_for :task_title %>
      </span>
      <%= link_to('(view raw output)', { format: :txt }) %>
    </div>

    <div class="deploy-banner-section action-buttons">
      <%= link_to abort_stack_task_path(@stack, task), class: "btn btn--alert action-button", data: { action: "abort", status: task.status } do %>
        <span class="caption--ready">Abort</span>
        <span class="caption--pending">Aborting...</span>
      <% end %>

      <% if task.supports_rollback? %>
        <%= link_to abort_stack_task_path(@stack, task, rollback: true), class: "btn btn--delete action-button", data: { action: "abort", rollback: true, status: task.status } do %>
          <span class="caption--ready">Abort and Rollback to <span class="short-sha-no-bg"><%= short_commit_sha(task) %></span></span>
          <span class="caption--pending">Aborting with Rollback... to <span class="short-sha-no-bg"><%= short_commit_sha(task) %></span></span>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="search-bar hidden">
    <input type="search" class="search-input" />
  </div>

  <div class="clusterize-scroll task-output-container task-output-container-main-page">
    <pre class="nowrap" data-status="<%= task.status %>"><code class="clusterize-content" data-output="<%= task.chunk_output %>" data-next-chunks-url="<%= next_chunks_url(task, last_byte: task.chunk_output_size) %>"></code></pre>
  </div>
</div>

app/views/shipit/tasks/index.html.erb
<%= render partial: 'shipit/stacks/header', locals: { stack: @stack } %>

<div class="wrapper">
  <section>
    <ul class="task-list">
      <%= render @tasks, read_only: true %>
    </ul>
  </section>
</div>

<div class="wrapper">
  <section class="pagination">
    <% if params[:since].present? %>
      <%= link_to 'Start', @links[:first], class: 'header__btn btn' %>
    <% else %>
      <%= link_to 'Start', '', class: 'header__btn btn btn--disabled disabled' %>
    <% end %>

    <% if url = @links[:next] %>
      <%= link_to 'Older', url, class: 'header__btn btn' %>
    <% else %>
      <%= link_to 'Older', '', class: 'header__btn btn btn--disabled disabled' %>
    <% end %>
  </section>
</div>

app/views/shipit/tasks/new.html.erb
<%= render partial: 'shipit/stacks/header', locals: { stack: @stack } %>

<div class="wrapper">
  <section>
    <header class="section-header">
      <p><%= @task.definition.description %></p>
    </header>
  </section>

  <section>
    <pre class="nowrap code-preview"><code><%= @task.definition.steps.join("\n") %></code></pre>
  </section>

  <%= render_checklist @task.checklist %>

  <%= form_for @task, url: stack_tasks_path(@stack, definition_id: @task.definition.id) do |f| %>

    <%= render partial: 'shipit/variables', locals: { variables: @task.definition.variables, form: f, header: "Environment Variables", field_name: :env}  %>

    <section class="submit-section">
      <% if !@task.definition.allow_concurrency? && @stack.active_task? %>
        <%= render 'shipit/deploys/concurrent_deploy_warning' %>
      <% end %>

      <%= f.submit @task.definition.action, :class => ['btn', 'primary', 'trigger-deploy'] %>
    </section>

  <% end %>
</div>

app/views/shipit/tasks/show.html.erb
<% content_for :task_title do %>
  <%= @task.active? ? "executing" : "executed" %> <%= @task.definition.id %>
  <%= timeago_tag(@task.created_at, force: true) %>
<% end %>

<%= render partial: 'shipit/tasks/task_output', locals: {task: @task} %>